version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:local
    volumes:
      - .:/data
    ports:
      - "3000:3000"
    working_dir: /data
    command: ["npm", "start"]
